# Generation of the HTML report 

import base64
from datetime import datetime
from config import OUTPUTS_DIR

def encode_image(image_path):
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

def generate_html(findings, report_content, run_id, username, pages):
    print("Generating HTML report...")

    critical = [f for f in findings if f["severity"] == "critical"]
    major = [f for f in findings if f["severity"] == "major"]
    minor = [f for f in findings if f["severity"] == "minor"]

    encoded_screenshots = {}
    for page in pages:
        try:
            encoded_screenshots[page["url"]] = encode_image(page["screenshot"])
        except Exception as e:
            print(f"  Could not encode screenshot for {page['url']}: {e}")

    def build_section(group, color, label):
        if not group:
            return f"<h2>{label}</h2><p><em>None found.</em></p>"

        cards = ""
        last_page_url = None
        for f in group:
            page_url = f["page_url"]
            screenshot_html = ""
            if page_url != last_page_url and page_url in encoded_screenshots:
                img_data = encoded_screenshots[page_url]
                screenshot_html = f"""
                <p><strong>Page:</strong> <code>{page_url}</code></p>
                <img src="data:image/png;base64,{img_data}"
                     alt="Screenshot of {page_url}"
                     style="width:100%; border:1px solid #ccc; margin: 8px 0 16px 0;"/>
                """
                last_page_url = page_url

            cards += f"""
            {screenshot_html}
            <div style="border-left: 3px solid {color}; padding: 10px 14px; margin-bottom: 12px; background: #fafafa;">
                <p><strong>[{f['severity'].upper()}]</strong> {f['issue_type'].upper()} — {f['description']}</p>
                <p><small><strong>Location:</strong> {f.get('location', 'Not specified')}</small></p>
                <p><small><strong>Recommended Fix:</strong> {f.get('recommended_fix', 'Not specified')}</small></p>
            </div>
            """
        return f"<h2>{label} ({len(group)})</h2>{cards}"

    critical_html = build_section(critical, "#cc0000", "Critical Findings")
    major_html = build_section(major, "#cc6600", "Major Findings")
    minor_html = build_section(minor, "#997700", "Minor Findings")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QA Report - {username}</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 960px; margin: 40px auto; padding: 0 20px; color: #222; }}
        h1 {{ border-bottom: 2px solid #222; padding-bottom: 10px; }}
        h2 {{ margin-top: 40px; border-bottom: 1px solid #ccc; padding-bottom: 6px; }}
        table {{ border-collapse: collapse; margin-bottom: 30px; }}
        td, th {{ padding: 6px 14px; border: 1px solid #ccc; font-size: 0.9em; }}
        code {{ background: #f0f0f0; padding: 2px 5px; font-size: 0.85em; }}
        .footer {{ margin-top: 60px; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 10px; }}
    </style>
</head>
<body>
    <h1>QA Automated Test Report</h1>
    <p>Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} | User Role: {username}</p>

    <h2>Test Details</h2>
    <table>
        <tr><th>Target Application</th><td>https://www.saucedemo.com</td></tr>
        <tr><th>User Role Tested</th><td>{username}</td></tr>
        <tr><th>Pages Analysed</th><td>{len(set(f['page_url'] for f in findings))}</td></tr>
        <tr><th>Total Issues</th><td>{len(findings)} ({len(critical)} critical, {len(major)} major, {len(minor)} minor)</td></tr>
        <tr><th>Run ID</th><td>{run_id}</td></tr>
    </table>

    {critical_html}
    {major_html}
    {minor_html}

    <div class="footer">Generated by QA Multi-Agent Pipeline | CM3070 Final Project</div>
</body>
</html>"""

    html_path = OUTPUTS_DIR / f"report_{run_id}_{username}.html"
    with open(html_path, "w", encoding="utf-8") as file:
        file.write(html)

    print(f"HTML report saved to {html_path}")
    return html_path